export enum CAMPAIGNS {
    JOURNIE_POT_LOYALTY_PROGRAM = 'Journie PoT Loyalty Program',
    JOURNIE_POT_LOYALTY_PROGRAM_ID = 'camp_d7nX6wuJJ60BbS0YaAAHa2zy',
    PROMO_POINTS_REWARDS_PROGRAM = '150 Point Rewards Program',
    PROMO_POINTS_REWARDS_PROGRAM_ID = 'camp_FS6X6mbMJH7WRS41HAXrsxc7',
    FREE_COCA_COCA_CAMPAIGN_ID = 'camp_QDL5yXJwM1gTo8pbBhRFVBtf',
}
