export enum CAMPAIGNS {
    LOYALTY_PROGRAM = 'Loyalty Program',
    LOYALTY_PROGRAM_ID = 'camp_uNiE8OM847iYYQcRizXGmFss',
    MILESTONE_REWARDS_PROGRAM = 'H-E-B Continuity',
    MILESTONE_REWARDS_PROGRAM_ID = 'camp_HQnS260WUa8wwyvVB5KKYuz0',
    FREE_COCA_COCA_CAMPAIGN_ID = 'camp_bSZ7k9kh8VUf2WFgK4TfwVx5',
    LOYALTY_PROGRAM_EARN_AND_BURN = 'H-E-B Loyalty',
    LOYALTY_PROGRAM_EARN_AND_BURN_ID = 'camp_6k2YGvptdN3e9pHYCLtE5o5J'
}
